name: Sync Docker Image To Aliyun

on:
  workflow_dispatch:
    inputs:
      source_image:
        description: 'Source image, example: nginx:latest or apache/kafka:latest'
        required: true
        default: 'apache/kafka:latest'
      target_repo:
        description: 'Aliyun repo name, example: nginx or kafka'
        required: true
        default: 'kafk'
      target_tag:
        description: 'Target tag'
        required: true
        default: 'latest'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Login Aliyun ACR
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login \
          --username="${{ secrets.ACR_USERNAME }}" \
          --password-stdin \
          ${{ secrets.ACR_REGISTRY }}

      - name: Pull source image
        run: |
          docker pull ${{ github.event.inputs.source_image }}

      - name: Tag image
        run: |
          docker tag ${{ github.event.inputs.source_image }} \
          ${{ secrets.ACR_REGISTRY }}/${{ secrets.ACR_NAMESPACE }}/${{ github.event.inputs.target_repo }}:${{ github.event.inputs.target_tag }}

      - name: Push image
        run: |
          docker push \
          ${{ secrets.ACR_REGISTRY }}/${{ secrets.ACR_NAMESPACE }}/${{ github.event.inputs.target_repo }}:${{ github.event.inputs.target_tag }}
